name: frontend
description: Projeto de Desenvolvimento Móvel.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.5
  intl: ^0.17.0
  file_picker: ^5.3.0
  flutter_staggered_grid_view: ^0.6.2
  provider: ^6.0.5
  uuid: ^3.0.7
  
  image_picker: ^0.8.7+5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
